[tool.poetry]
name = "python-skeleton"
version = "0.1.0"
description = ""
authors = ["e.nakhle <elio.nakhle@agile-robots.com>"]
readme = "README.md"
packages = [{include = "python_skeleton"}]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"


[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
coverage = {extras = ["toml"], version = "^6.4.4"}
pytest-cov = "^3.0.0"
nox = "^2022.8.7"
black = "^22.8.0"
flake8 = "^5.0.4"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.9.23"
flake8-import-order = "^0.18.1"
mypy = "^0.981"
flake8-docstrings = "^1.6.0"
darglint = "^1.8.1"
Sphinx = "^5.2.2"
sphinx-autodoc-typehints = "^1.19.4"
codecov = "^2.1.12"
isort = "^5.10.1"
flake8-annotations = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
project-name = "python_skeleton.project_name.console:main"

[tool.coverage.paths]
source = ["python_skeleton", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["python_skeleton"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.black]
line-length = 99

[tool.mypy]
ignore_missing_imports = true
